name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Files From Current Directory
        uses: actions/checkout@v3
      - name: Prepare Dependencies
        run: egrep -R --exclude-dir=node_modules '=\s*require\\s*\(' |awk '{gsub(/^.+require\s*\(\s*./,""); gsub(/.\s*\).*$/,""); print $0}' | xargs npm install && npm i && npm ci
      
      - name: Deploy to Firebase Live Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_QRACH_PROX }}"
          channelId: live
          projectId: qrach-prox
