name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Dependencies
      - uses: actions/checkout@v2
      - run: npm run build
      
      - name: Deploy to Firebase Live Channel
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_QRACH_PROX }}"
          channelId: live
          projectId: qrach-prox
